# Generated by Django 5.0.6 on 2024-06-16 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calory_calculator', '0002_foodimage_delete_calory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodimage',
            old_name='quantity',
            new_name='grams',
        ),
        migrations.AlterField(
            model_name='foodimage',
            name='food_name',
            field=models.CharField(blank=True, help_text='Optional', max_length=100, null=True),
        ),
    ]
