# Generated by Django 5.0.6 on 2024-06-16 23:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calory_calculator', '0003_rename_quantity_foodimage_grams_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodimage',
            old_name='date_added',
            new_name='uploaded_at',
        ),
        migrations.AddField(
            model_name='foodimage',
            name='calories',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='foodimage',
            name='food_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodimage',
            name='grams',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='foodimage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
