# Generated by Django 5.0.6 on 2024-06-16 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calory_calculator', '0004_rename_date_added_foodimage_uploaded_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodimage',
            name='additional_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
