# Generated by Django 5.0.6 on 2024-06-16 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calory_calculator', '0005_foodimage_additional_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodimage',
            name='calories',
            field=models.TextField(blank=True, null=True),
        ),
    ]
