# Generated by Django 5.0.6 on 2024-06-08 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_profile_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='country_code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
