# Generated by Django 5.0.6 on 2024-06-08 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_profile_country_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='country_code',
        ),
    ]
