# Generated by Django 5.0.6 on 2024-06-08 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_profile_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='country_code',
        ),
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
