# Generated by Django 5.0.6 on 2024-06-09 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_additional_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additional_info',
            name='additional_information',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='additional_info',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='additional_info',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='additional_info',
            name='medical_history',
            field=models.TextField(blank=True, null=True),
        ),
    ]
