# Generated by Django 5.0.6 on 2024-06-09 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_profile_country'),
        ('account', '0012_alter_additional_info_additional_information_and_more'),
    ]

    operations = [
    ]
