# Generated by Django 5.0.6 on 2024-06-09 22:52

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_merge_20240609_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=django_countries.fields.CountryField(default='US', max_length=2),
        ),
    ]
