# Generated by Django 5.0.6 on 2024-06-12 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_remove_profile_bio_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='additional_info',
            name='bio',
            field=models.CharField(blank=True),
        ),
    ]
