# Generated by Django 5.0.6 on 2024-06-12 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_additional_info_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additional_info',
            name='bio',
        ),
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, null=True),
        ),
    ]
