# Generated by Django 5.0.6 on 2024-06-09 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptom_checker', '0002_symptomchecker_delete_symptom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='symptomchecker',
            name='location',
        ),
        migrations.AlterField(
            model_name='symptomchecker',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
    ]
