# Generated by Django 5.0.6 on 2024-06-21 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medication_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicationreminder',
            name='notes',
            field=models.TextField(default='no notes'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medicationreminder',
            name='medication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='medication_management.medication'),
        ),
    ]
