# Generated by Django 5.0.6 on 2024-06-08 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptom_checker', '0002_symptomchecker_delete_symptom'),
        ('workout_training', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthdata',
            name='symptoms',
            field=models.ManyToManyField(related_name='health_data', to='symptom_checker.symptomchecker'),
        ),
    ]
